package com.jain.core.registry;

import com.jain.core.lexicon.Lexical;

/**
 * Hindi: {@code Tattv} vriksh ke node.
 * English: High-level concepts in the ontology graph.
 */
public enum Concept implements Lexical {
    ACHAKSHU_DARSHANAVARNIYA("Achakshu — Non-sight perception obscuring", false),
    ADEYA_FULLY("Adeya — Acceptable or convincing", false),
    ADEYA_NAM("Adeya — Acceptable or authoritative speech", false),
    ADHARM("Adharmastikay — Medium of rest: supports rest without itself stopping", false),
    AGHAATI("Aghati Karma — Non-destructive karmas: shape embodied conditions", false),
    AHARAK("Aharak Vargana — Projected or communication body matter", false),
    AHARAKA_ANGOPANGA("Aharaka angopanga — Projected body parts", false),
    AHARAKA_SHARIRA("Aharaka sharira — Projected body", false),
    AJIV("Ajiv — Non-living substance: without consciousness", false),
    AKASH("Akashastikay — Space: accommodates all substances", false),
    ALOKAKASH("Alokakash — Empty space: beyond the occupied universe", false),
    AMLA_RASA("Amla — Sour body taste", false),
    ANADEYA_FULLY("Anadeya — Unacceptable or unconvincing", false),
    ANADEYA_NAM("Anadeya — Unacceptable or unconvincing speech", false),
    ANGOPANGA_NAM("Angopanga — Body-part determining", false),
    ANTARAY("Antaray — Obstruction-causing karma", false),
    ANTARAY_CLASSIFICATION("Antaray Prakritis — Five obstruction subtypes", true),
    ANUPURVI_NAM("Anupurvi — Direction of rebirth movement", false),
    APARYAPTA_FULLY("Aparyapta — Incomplete bodily development", false),
    APARYAPTA_NAM("Aparyapta — Underdeveloped faculties", false),
    APKAY("Apkay — Water-bodied: life associated with water matter", false),
    APRASASTA_VIHAYOGATI("Aprasasta vihayogati — Unpleasant movement", false),
    ARATI("Arati — Dislike or aversion", false),
    ARDH_NARACA("Ardha-naraca — Partial binding", false),
    ASAINI("Asaini — Without mind: instinctive or mindless", false),
    ASHATA_VEDNIYA("Ashata — Pain-producing feeling", false),
    ASTHIRA_FULLY("Asthira — Flexibility of organs", false),
    ASTHIRA_NAM("Asthira — Flexibility of body parts", false),
    ASTIKAAY("Astikaya — Extensive substances: occupy multiple space-points", false),
    ASTRINGENT("Astringent — one of the five tastes", false),
    ASUBHA_FULLY("Asubha — Unbeautiful features", false),
    ASUBHA_NAM("Asubha — Unbeautiful bodily formation", false),
    AUDARIK("Audarik Vargana — Physical body matter", false),
    AUDARIKA_ANGOPANGA("Audarika angopanga — Gross body parts", false),
    AUDARIKA_SHARIRA("Audarika sharira — Gross physical body", false),
    AVADHI_DARSHANAVARNIYA("Avadhi — Clairvoyant perception obscuring", false),
    AVADHI_JNANAVARNIYA("Avadhi — Clairvoyant knowledge obscuring", false),
    AVALI("Avali — Countless samays: practical bundle of time-instants", false),
    AYASHAHKIRTI_FULLY("Ayashahkirti — Shame and dishonour", false),
    AYASHAHKIRTI_NAM("Ayashahkirti — Dishonour and infamy", false),
    AYUSHYA("Ayushya — Life-span-determining karma", false),
    AYUSHYA_CLASSIFICATION("Ayushya Types — Four life-span subtypes", true),
    AYUSHYA_PRANA("Ayushya Prana — Life-span vitality", false),
    BAD_SMELL("Bad smell — one of the two odours", false),
    BADAR_JEEV("Badar — Gross: visible or obstructed", false),
    BADARA_FULLY("Badara — Gross body development", false),
    BADARA_NAM("Badara — Gross body tendency", false),
    BALA_PRANA("Bala Prana — Three forces vitality", false),
    BHASHA("Bhasha Vargana — Speech matter", false),
    BHAYA("Bhaya — Fear", false),
    BHOGA_ANTARAY("Bhoga — Enjoyment obstructing", false),
    BITTER("Bitter — one of the five tastes", false),
    BLACK("Black — one of the five primary colours", false),
    BLUE("Blue — one of the five primary colours", false),
    CATURINDRIYA_JATI("Caturindriya — Four-sensed birth", false),
    CHAKSHU_DARSHANAVARNIYA("Chakshu — Sight perception obscuring", false),
    CHAKSHU_INDRIYA("Chakshu — Vision vitality", false),
    CHARITRA_MOHANIYA("Charitra Mohaniya — Conduct-deluding branch", false),
    CHARITRA_MOHANIYA_CLASSIFICATION("Charitra Mohaniya Types — Conduct-deluding subtypes", true),
    CHAURINDRIYA("Chaurindriya — Four-sensed: adds sight", false),
    COLD("Cold — one of the eight touches", false),
    COLOUR("Varna — Colour property", false),
    DANA_ANTARAY("Dana — Donation obstructing", false),
    DARSHANA_MOHANIYA("Darshana Mohaniya — Faith-deluding branch", false),
    DARSHANA_MOHANIYA_CLASSIFICATION("Darshana Mohaniya Types — Three faith-deluding subtypes", true),
    DARSHANAVARNIYA("Darshanavarniya — Perception-obscuring karma", false),
    DARSHANAVARNIYA_CLASSIFICATION("Darshanavarniya Prakritis — Nine perception-obscuring subtypes", true),
    DEV("Dev — Celestial realm beings", false),
    DEVA_ANUPURVI("Deva anupurvi — Direction toward celestial birth", false),
    DEVA_AYU("Deva — Celestial life-span", false),
    DEVA_GATI_NAM("Deva gati — Celestial state determining", false),
    DHARM("Dharmastikay — Medium of motion: supports movement without itself moving", false),
    DRAVYA("Dravya — Substance: fundamental reality with qualities and modes", false),
    DUHSVARA_FULLY("Duhsvara — Harsh speech", false),
    DUHSVARA_NAM("Duhsvara — Harsh voice", false),
    DURABHI_GANDHA("Durabhi — Unpleasant smell", false),
    DURBHAGA_FULLY("Durbhaga — Unpleasing or unfortunate", false),
    DURBHAGA_NAM("Durbhaga — Unpleasant or unlovable", false),
    DVINDRIYA_JATI("Dvindriya — Two-sensed birth", false),
    DWINDRIYA("Dwindriya — Two-sensed: touch and taste", false),
    EIGHT_TOUCH("Eight-touch — Gross matter level", false),
    EKENDRIYA_JATI("Ekendriya — One-sensed birth", false),
    FOUR_TOUCH("Four-touch — Subtle matter level", false),
    FUNCTION_CLASSIFICATION("Function — Classification by karmic or bodily role", true),
    GANDHA_NAM("Gandha — Body smell", false),
    GATI_CLASSIFICATION("Gati — Realm of rebirth classification", true),
    GATI_NAM("Gati — Four states of existence", false),
    GHAATI("Ghati Karma — Destructive karmas: obstruct soul qualities", false),
    GHRAN_INDRIYA("Ghran — Smell vitality", false),
    GOOD_SMELL("Good smell — one of the two odours", false),
    GOTRA("Gotra — Status-determining karma", false),
    GOTRA_CLASSIFICATION("Gotra Types — Two status subtypes", true),
    GURU_SPARSHA("Guru — Heavy touch", false),
    HARD("Kathor — Hard touch", false),
    HARITA_VARNA("Harita — Yellow body colour", false),
    HASYA("Hasya — Laughter or joking", false),
    HEAVY("Guru — Heavy touch", false),
    HOT("Hot — one of the eight touches", false),
    HUNDA("Hunda — Deformed form", false),
    INDRIYA_PRANA("Indriya Prana — Five senses vitality", false),
    JATI_NAM("Jati — Five classes of beings", false),
    JEEV("Jeev — Soul: conscious, sentient substance with knowledge and perception", false),
    JNANAVARNIYA("Jnanavarniya — Knowledge-obscuring karma", false),
    JNANAVARNIYA_CLASSIFICATION("Jnanavarniya Prakritis — Five knowledge-obscuring subtypes", true),
    JUGUPSA("Jugupsa — Disgust", false),
    KAAL("Kaal — Time: enables sequence, change, and duration", false),
    KARM("Karman Vargana — Karmic matter", false),
    KARMANA_SHARIRA("Karmana sharira — Karmic body", false),
    KASAYA_RASA("Kasaya — Astringent body taste", false),
    KASHAYA("Kashaya — Passions: anger, pride, deceit, greed", false),
    KASHAYA_CLASSIFICATION("Kashaya Grouping — Sixteen passion subtypes by intensity", true),
    KATHOR_SPARSHA("Kathor — Hard touch", false),
    KATU_RASA("Katu — Pungent body taste", false),
    KAYA_BALA("Kaya-bal — Body vitality", false),
    KEVALA_DARSHANAVARNIYA("Kevala — Omniperception obscuring", false),
    KEVALA_JNANAVARNIYA("Kevala — Omniscient knowledge obscuring", false),
    KILIKA("Kilika — Weak binding", false),
    KRISHNA_VARNA("Krishna — Black body colour", false),
    KRODH("Krodh — Anger", false),
    KRODH_ANANTANUBANDHI("Anantanubandhi Krodh — Endless binding anger", false),
    KRODH_APRATYAKHYANAVARANIYA("Apratyakhyanavaraniya Krodh — Prevents partial vows", false),
    KRODH_PRATYAKHYANAVARANIYA("Pratyakhyanavaraniya Krodh — Prevents full vows", false),
    KRODH_SANJVALAN("Sanjvalan Krodh — Burning, momentary anger", false),
    KUBJA("Kubja — Hunchbacked form", false),
    LABHA_ANTARAY("Labha — Gain obstructing", false),
    LAGHU_SPARSHA("Laghu — Light touch", false),
    LIGHT("Laghu — Light touch", false),
    LOBH("Lobh — Greed", false),
    LOBH_ANANTANUBANDHI("Anantanubandhi Lobh — Endless binding greed", false),
    LOBH_APRATYAKHYANAVARANIYA("Apratyakhyanavaraniya Lobh — Prevents partial vows", false),
    LOBH_PRATYAKHYANAVARANIYA("Pratyakhyanavaraniya Lobh — Prevents full vows", false),
    LOBH_SANJVALAN("Sanjvalan Lobh — Burning, momentary greed", false),
    LOHITA_VARNA("Lohita — Red body colour", false),
    LOKAKASH("Lokakash — Occupied universe: region where substances exist", false),
    MAAN("Maan — Pride", false),
    MAAN_ANANTANUBANDHI("Anantanubandhi Maan — Endless binding pride", false),
    MAAN_APRATYAKHYANAVARANIYA("Apratyakhyanavaraniya Maan — Prevents partial vows", false),
    MAAN_PRATYAKHYANAVARANIYA("Pratyakhyanavaraniya Maan — Prevents full vows", false),
    MAAN_SANJVALAN("Sanjvalan Maan — Burning, momentary pride", false),
    MADHURA_RASA("Madhura — Sweet body taste", false),
    MANAH("Manah Vargana — Mind matter", false),
    MANAHPARYAYA_JNANAVARNIYA("Manahparyaya — Telepathic knowledge obscuring", false),
    MANO_BALA("Mano-bal — Mind vitality", false),
    MANUSHYA("Manushya — Human realm beings", false),
    MANUSHYA_ANUPURVI("Manushya anupurvi — Direction toward human birth", false),
    MANUSHYA_AYU("Manushya — Human life-span", false),
    MANUSHYA_GATI_NAM("Manushya gati — Human state determining", false),
    MATI_JNANAVARNIYA("Mati — Sensory and mental knowledge obscuring", false),
    MAYA("Maya — Deceit", false),
    MAYA_ANANTANUBANDHI("Anantanubandhi Maya — Endless binding deceit", false),
    MAYA_APRATYAKHYANAVARANIYA("Apratyakhyanavaraniya Maya — Prevents partial vows", false),
    MAYA_PRATYAKHYANAVARANIYA("Pratyakhyanavaraniya Maya — Prevents full vows", false),
    MAYA_SANJVALAN("Sanjvalan Maya — Burning, momentary deceit", false),
    MISHRA("Mishra — Mixed or partially right faith", false),
    MITHYATVA("Mithyatva — False faith or wrong belief", false),
    MOHANIYA("Mohaniya — Deluding karma", false),
    MOHANIYA_CLASSIFICATION("Mohaniya Prakritis — Twenty-eight deluding subtypes", true),
    MRIDU_SPARSHA("Mridu — Soft touch", false),
    MUKTA("Mukta — Liberated souls: free from karma and dwelling in pure state", false),
    MURTA("Murta — Corporeal: perceptible through the senses", false),
    NAM("Nam — Body-determining karma", false),
    NAM_CLASSIFICATION("Nam Karma Prakritis — Main body-making groupings and finer subtypes", true),
    NAPUMSAKAVEDA("Napumsakaveda — Neuter passion", false),
    NARACA("Naraca — Moderate binding", false),
    NARAK("Narak — Infernal realm beings", false),
    NARAKA_ANUPURVI("Naraka anupurvi — Direction toward infernal birth", false),
    NARAKA_AYU("Naraka — Infernal life-span", false),
    NARAKA_GATI_NAM("Naraka gati — Infernal state determining", false),
    NASTIKAY("Anastikaya — Non-extensive substance: does not occupy multiple space-points", false),
    NEECHA_GOTRA("Neecha — Low status", false),
    NIDRA("Nidra — Ordinary sleep", false),
    NIDRA_NIDRA("Nidra-Nidra — Deep sleep, hard to awaken from", false),
    NILA_VARNA("Nila — Blue body colour", false),
    NOKASHAYA("Nokashaya — Non-passions: softer conduct-deluding states", false),
    NOKASHAYA_CLASSIFICATION("Nokashaya Grouping — Nine non-passion subtypes", true),
    NYAGRODHAPARIMANDALA("Nyagrodhaparimandala — Upper body symmetry", false),
    PANCHENDRIYA("Panchendriya — Five-sensed: adds hearing", false),
    PANCHENDRIYA_JATI("Panchendriya — Five-sensed birth", false),
    PARAMANU("Paramanu — Atom: smallest indivisible unit of matter", false),
    PARYAPTA_FULLY("Paryapta — Complete bodily development", false),
    PARYAPTA_NAM("Paryapta — Fully developed faculties", false),
    PRACHALA("Prachala — Sleep even while active", false),
    PRACHALA_PRACHALA("Prachala-Prachala — Very intense sleep state", false),
    PRANA_CLASSIFICATION("Prana — Vitalities classification", true),
    PRASASTA_VIHAYOGATI("Prasasta vihayogati — Pleasant movement", false),
    PRATYEK("Pratyek — Individual plant soul: one soul per body", false),
    PRATYEKA_FULLY("Pratyeka — Individual embodiment", false),
    PRATYEKA_NAM("Pratyeka — Individual body", false),
    PRITHVIKAY("Prithvikay — Earth-bodied: life associated with earth matter", false),
    PUDGAL("Pudgalastikay — Matter: only corporeal, perceivable substance", false),
    PUDGAL_QUALITY_CLASSIFICATION("Quality Set — Classification by colour, taste, smell, touch", true),
    PUNGENT("Pungent — one of the five tastes", false),
    PURUSHVEDA("Purushveda — Male passion", false),
    QUALITY_COLOUR("Varna-set — five primary colours", false),
    QUALITY_SET("Guna-set — Possesses colour, taste, smell, and touch", false),
    QUALITY_SMELL("Gandha-set — two smells", false),
    QUALITY_TASTE("Rasa-set — five tastes", false),
    QUALITY_TOUCH("Sparsha-set — eight touches", false),
    RAS_INDRIYA("Ras — Taste vitality", false),
    RASA_NAM("Rasa — Body taste", false),
    RATI("Rati — Attachment or liking", false),
    RED("Red — one of the five primary colours", false),
    ROUGH("Ruksha — Rough or negative-charge touch", false),
    RSABHANARACA("Rsabhanaraca — Strong binding", false),
    RUKSHA_SPARSHA("Ruksha — Rough touch", false),
    RUPATVA("Rupatva — Sensory manifestation: defined by material qualities", false),
    SADHARAN("Sadharan — Common/Nigod: many souls sharing one body", false),
    SADHARANA_FULLY("Sadharana — Shared embodiment", false),
    SADHARANA_NAM("Sadharana — Common body", false),
    SADI("Sadi — Lower body symmetry", false),
    SAINI("Saini — With mind: sentient and reflective", false),
    SAMACATURASRA("Samacaturasra — Symmetrical body", false),
    SAMAY("Samay — Ultimate unit: indivisible instant of time", false),
    SAMHANANA_NAM("Samhanana — Joint structure and bone binding", false),
    SAMSTHANA_NAM("Samsthana — Bodily symmetry and form", false),
    SAMYAKTVA_MOHANIYA("Samyaktva Mohaniya — Right faith obscuring delusion", false),
    SANSARI("Sansari — Worldly souls: bound by karma and subject to rebirth", false),
    SEVARTTA("Sevartta — Very weak binding", false),
    SHARIRA_NAM("Sharira — Five body types", false),
    SHATA_VEDNIYA("Shata — Pleasure-producing feeling", false),
    SHEETA_SPARSHA("Sheeta — Cold touch", false),
    SHOK("Shok — Sorrow", false),
    SHRAVAN_INDRIYA("Shravan — Hearing vitality", false),
    SHRUT_JNANAVARNIYA("Shrut — Scriptural or learned knowledge obscuring", false),
    SHVASOCHCHHVAS_PRANA("Shvasochchhvas Prana — Respiration vitality", false),
    SHVASOCHHVAS("Shvasochhvas Vargana — Respiratory matter", false),
    SKANDH("Skandh — Aggregate: cluster of atoms", false),
    SMELL("Gandha — Smell property", false),
    SMOOTH("Snigdha — Smooth or positive-charge touch", false),
    SNIGDHA_SPARSHA("Snigdha — Smooth touch", false),
    SOFT("Mridu — Soft touch", false),
    SOUR("Sour — one of the five tastes", false),
    SPARSH_INDRIYA("Sparsh — Touch vitality", false),
    SPARSHA_NAM("Sparsha — Body touch", false),
    STATE_CLASSIFICATION("State — Classification by perceptibility and fineness", true),
    STHAVAR("Sthavar — Immobile beings: one-sensed life forms", false),
    STHAVAR_SIZE("Sthavar Size — Classification by pervasiveness and visibility", true),
    STHAVARA_FULLY("Sthavara — Immobile beings and stillness", false),
    STHAVARA_NAM("Sthavara — Immobile body tendency", false),
    STHIRA_FULLY("Sthira — Stability of organs", false),
    STHIRA_NAM("Sthira — Firmness of body parts", false),
    STHULA("Sthula — Liquid matter, like water or oil", false),
    STHULA_STHULA("Sthula-Sthula — Gross solid matter, like wood or stone", false),
    STHULA_SUKSHMA("Sthula-Sukshma — Visible but untouchable, like light or shadow", false),
    STRIVEDA("Striveda — Female passion", false),
    STRUCTURE_CLASSIFICATION("Structure — Classification by form and aggregation", true),
    STYANARDDHI("Styanarddhi — Sleep-like dullness or psychic stupor", false),
    SUBHA_FULLY("Subha — Beautiful features", false),
    SUBHA_NAM("Subha — Beautiful bodily formation", false),
    SUBHAGA_FULLY("Subhaga — Pleasing or fortunate", false),
    SUBHAGA_NAM("Subhaga — Pleasant or lovable", false),
    SUKLA_VARNA("Sukla — White body colour", false),
    SUKSHMA("Sukshma — Subtle matter, including karmic matter", false),
    SUKSHMA_FULLY("Sukshma — Minute body development", false),
    SUKSHMA_JEEV("Sukshma — Minute: pervasive or unobstructed", false),
    SUKSHMA_NAM("Sukshma — Subtle body tendency", false),
    SUKSHMA_STHULA("Sukshma-Sthula — Invisible but sensible, like air or smell", false),
    SUKSHMA_SUKSHMA("Sukshma-Sukshma — Ultra-subtle matter, atom-like", false),
    SURABHI_GANDHA("Surabhi — Pleasant smell", false),
    SUSVARA_FULLY("Susvara — Pleasant speech", false),
    SUSVARA_NAM("Susvara — Sweet voice", false),
    SWEET("Sweet — one of the five tastes", false),
    TAIJAS("Taijas Vargana — Luminous or fiery body matter", false),
    TAIJASA_SHARIRA("Taijasa sharira — Fiery or luminous body", false),
    TASTE("Rasa — Taste property", false),
    TEUKAY("Teukay — Fire-bodied: life associated with fire matter", false),
    TIKTA_RASA("Tikta — Bitter body taste", false),
    TIRYAG_GATI_NAM("Tiryag gati — Animal state determining", false),
    TIRYANCH("Tiryanch — Animal/plant realm beings", false),
    TIRYANCH_ANUPURVI("Tiryanch anupurvi — Direction toward animal birth", false),
    TIRYANCH_AYU("Tiryanch — Animal life-span", false),
    TOUCH("Sparsha — Touch property", false),
    TOUCH_BASED_CLASSIFICATION("Touch-based — Classification by touch count", true),
    TRAS("Tras — Mobile beings: two to five sensed life forms", false),
    TRASA_FULLY("Trasa — Mobile beings and mobility", false),
    TRASA_NAM("Trasa — Mobile body tendency", false),
    TRINDRIYA("Trindriya — Three-sensed: touch, taste, smell", false),
    TRINDRIYA_JATI("Trindriya — Three-sensed birth", false),
    TWO_TOUCH("Two-touch — Minimal matter level: paramanu", false),
    UCCHA_GOTRA("Uccha — High status", false),
    UPABHOGA_ANTARAY("Upabhoga — Re-enjoyment obstructing", false),
    USHNA_SPARSHA("Ushna — Hot touch", false),
    VACHAN_BALA("Vachan-bal — Speech vitality", false),
    VAIKRIYA("Vaikriya Vargana — Transformable body matter", false),
    VAIKRIYA_ANGOPANGA("Vaikriya angopanga — Transformable body parts", false),
    VAIKRIYA_SHARIRA("Vaikriya sharira — Transformable body", false),
    VAJRA_RSABHANARACA("Vajra-rsabhanaraca — Highest bone binding", false),
    VAMANA("Vamana — Dwarf-like form", false),
    VANASPATIKAY("Vanaspatikay — Plant-bodied: vegetation life", false),
    VARGAN("Vargana — Functional clusters of matter", false),
    VARNA_NAM("Varna — Body colour", false),
    VAYUKAY("Vayukay — Air-bodied: life associated with air matter", false),
    VEDNIYA("Vedniya — Feeling-producing karma", false),
    VEDNIYA_CLASSIFICATION("Vedniya Types — Two feeling-producing subtypes", true),
    VIHAYOGATI_NAM("Vihayogati — Mode of movement", false),
    VIRYA_ANTARAY("Virya — Energy obstructing", false),
    WHITE("White — one of the five primary colours", false),
    YASHAHKIRTI_FULLY("Yashahkirti — Fame and honour", false),
    YASHAHKIRTI_NAM("Yashahkirti — Honour and fame", false),
    YELLOW("Yellow — one of the five primary colours", false);

    private final String englishMeaning;
    private final boolean isClassificationCriterion;

    Concept(String englishMeaning, boolean isClassificationCriterion) {
        this.englishMeaning = englishMeaning;
        this.isClassificationCriterion = isClassificationCriterion;
    }

    @Override
    public String englishMeaning() {
        return englishMeaning;
    }

    public boolean isClassificationCriterion() {
        return isClassificationCriterion;
    }
}
