package com.jain.core.registry;

/**
 * Hindi: {@code Tattv} kosh.
 * English: Builds the complete ontology graph from the domain mermaid diagram.
 */
public final class OntologyRegistry {
    public OntologyNode root() {
        OntologyNode dravya = new OntologyNode(Concept.DRAVYA);
        OntologyNode astikay = new OntologyNode(Concept.ASTIKAAY);
        OntologyNode nastikay = new OntologyNode(Concept.NASTIKAY);
        OntologyNode kaal = new OntologyNode(Concept.KAAL);
        OntologyNode samay = new OntologyNode(Concept.SAMAY);
        OntologyNode avali = new OntologyNode(Concept.AVALI);
        OntologyNode jeev = new OntologyNode(Concept.JEEV);
        OntologyNode ajiv = new OntologyNode(Concept.AJIV);
        OntologyNode dharm = new OntologyNode(Concept.DHARM);
        OntologyNode adharm = new OntologyNode(Concept.ADHARM);
        OntologyNode akash = new OntologyNode(Concept.AKASH);
        OntologyNode pudgal = new OntologyNode(Concept.PUDGAL);
        OntologyNode lokakash = new OntologyNode(Concept.LOKAKASH);
        OntologyNode alokakash = new OntologyNode(Concept.ALOKAKASH);
        OntologyNode mukta = new OntologyNode(Concept.MUKTA);
        OntologyNode sansari = new OntologyNode(Concept.SANSARI);
        OntologyNode sthavar = new OntologyNode(Concept.STHAVAR);
        OntologyNode tras = new OntologyNode(Concept.TRAS);
        OntologyNode prithvikay = new OntologyNode(Concept.PRITHVIKAY);
        OntologyNode apkay = new OntologyNode(Concept.APKAY);
        OntologyNode teukay = new OntologyNode(Concept.TEUKAY);
        OntologyNode vayukay = new OntologyNode(Concept.VAYUKAY);
        OntologyNode vanaspatikay = new OntologyNode(Concept.VANASPATIKAY);
        OntologyNode pratyek = new OntologyNode(Concept.PRATYEK);
        OntologyNode sadharan = new OntologyNode(Concept.SADHARAN);
        OntologyNode sthavarsize = new OntologyNode(Concept.STHAVAR_SIZE);
        OntologyNode badarjeev = new OntologyNode(Concept.BADAR_JEEV);
        OntologyNode sukshmajeev = new OntologyNode(Concept.SUKSHMA_JEEV);
        OntologyNode dwindriya = new OntologyNode(Concept.DWINDRIYA);
        OntologyNode trindriya = new OntologyNode(Concept.TRINDRIYA);
        OntologyNode chaurindriya = new OntologyNode(Concept.CHAURINDRIYA);
        OntologyNode panchendriya = new OntologyNode(Concept.PANCHENDRIYA);
        OntologyNode saini = new OntologyNode(Concept.SAINI);
        OntologyNode asaini = new OntologyNode(Concept.ASAINI);
        OntologyNode gaticlassification = new OntologyNode(Concept.GATI_CLASSIFICATION);
        OntologyNode dev = new OntologyNode(Concept.DEV);
        OntologyNode manushya = new OntologyNode(Concept.MANUSHYA);
        OntologyNode tiryanch = new OntologyNode(Concept.TIRYANCH);
        OntologyNode narak = new OntologyNode(Concept.NARAK);
        OntologyNode pranaclassification = new OntologyNode(Concept.PRANA_CLASSIFICATION);
        OntologyNode indriyaprana = new OntologyNode(Concept.INDRIYA_PRANA);
        OntologyNode balaprana = new OntologyNode(Concept.BALA_PRANA);
        OntologyNode ayushyaprana = new OntologyNode(Concept.AYUSHYA_PRANA);
        OntologyNode shvasochchhvasprana = new OntologyNode(Concept.SHVASOCHCHHVAS_PRANA);
        OntologyNode sparshindriya = new OntologyNode(Concept.SPARSH_INDRIYA);
        OntologyNode rasindriya = new OntologyNode(Concept.RAS_INDRIYA);
        OntologyNode ghranindriya = new OntologyNode(Concept.GHRAN_INDRIYA);
        OntologyNode chakshuindriya = new OntologyNode(Concept.CHAKSHU_INDRIYA);
        OntologyNode shravanindriya = new OntologyNode(Concept.SHRAVAN_INDRIYA);
        OntologyNode manobala = new OntologyNode(Concept.MANO_BALA);
        OntologyNode vachanbala = new OntologyNode(Concept.VACHAN_BALA);
        OntologyNode kayabala = new OntologyNode(Concept.KAYA_BALA);
        OntologyNode murta = new OntologyNode(Concept.MURTA);
        OntologyNode rupatva = new OntologyNode(Concept.RUPATVA);
        OntologyNode colour = new OntologyNode(Concept.COLOUR);
        OntologyNode taste = new OntologyNode(Concept.TASTE);
        OntologyNode smell = new OntologyNode(Concept.SMELL);
        OntologyNode touch = new OntologyNode(Concept.TOUCH);
        OntologyNode black = new OntologyNode(Concept.BLACK);
        OntologyNode blue = new OntologyNode(Concept.BLUE);
        OntologyNode red = new OntologyNode(Concept.RED);
        OntologyNode yellow = new OntologyNode(Concept.YELLOW);
        OntologyNode white = new OntologyNode(Concept.WHITE);
        OntologyNode sweet = new OntologyNode(Concept.SWEET);
        OntologyNode bitter = new OntologyNode(Concept.BITTER);
        OntologyNode pungent = new OntologyNode(Concept.PUNGENT);
        OntologyNode sour = new OntologyNode(Concept.SOUR);
        OntologyNode astringent = new OntologyNode(Concept.ASTRINGENT);
        OntologyNode goodsmell = new OntologyNode(Concept.GOOD_SMELL);
        OntologyNode badsmell = new OntologyNode(Concept.BAD_SMELL);
        OntologyNode cold = new OntologyNode(Concept.COLD);
        OntologyNode hot = new OntologyNode(Concept.HOT);
        OntologyNode smooth = new OntologyNode(Concept.SMOOTH);
        OntologyNode rough = new OntologyNode(Concept.ROUGH);
        OntologyNode light = new OntologyNode(Concept.LIGHT);
        OntologyNode heavy = new OntologyNode(Concept.HEAVY);
        OntologyNode soft = new OntologyNode(Concept.SOFT);
        OntologyNode hard = new OntologyNode(Concept.HARD);
        OntologyNode stateclassification = new OntologyNode(Concept.STATE_CLASSIFICATION);
        OntologyNode structureclassification = new OntologyNode(Concept.STRUCTURE_CLASSIFICATION);
        OntologyNode touchbasedclassification = new OntologyNode(Concept.TOUCH_BASED_CLASSIFICATION);
        OntologyNode functionclassification = new OntologyNode(Concept.FUNCTION_CLASSIFICATION);
        OntologyNode pudgalqualityclassification = new OntologyNode(Concept.PUDGAL_QUALITY_CLASSIFICATION);
        OntologyNode aharmethodology = new OntologyNode(Concept.AHAR_METHODOLOGY);
        OntologyNode ojahar = new OntologyNode(Concept.OJ_AHAR);
        OntologyNode romahar = new OntologyNode(Concept.ROM_AHAR);
        OntologyNode kavalahar = new OntologyNode(Concept.KAVAL_AHAR);
        OntologyNode lepahar = new OntologyNode(Concept.LEP_AHAR);
        OntologyNode manasahar = new OntologyNode(Concept.MANAS_AHAR);
        OntologyNode karmanahar = new OntologyNode(Concept.KARMAN_AHAR);
        OntologyNode kavalaharclassification = new OntologyNode(Concept.KAVAL_AHAR_CLASSIFICATION);
        OntologyNode asanam = new OntologyNode(Concept.ASANAM);
        OntologyNode paanam = new OntologyNode(Concept.PAANAM);
        OntologyNode khaimam = new OntologyNode(Concept.KHAIMAM);
        OntologyNode saimam = new OntologyNode(Concept.SAIMAM);
        OntologyNode sthulasthula = new OntologyNode(Concept.STHULA_STHULA);
        OntologyNode sthula = new OntologyNode(Concept.STHULA);
        OntologyNode sthulasukshma = new OntologyNode(Concept.STHULA_SUKSHMA);
        OntologyNode sukshmasthula = new OntologyNode(Concept.SUKSHMA_STHULA);
        OntologyNode sukshma = new OntologyNode(Concept.SUKSHMA);
        OntologyNode sukshmasukshma = new OntologyNode(Concept.SUKSHMA_SUKSHMA);
        OntologyNode paramanu = new OntologyNode(Concept.PARAMANU);
        OntologyNode skandh = new OntologyNode(Concept.SKANDH);
        OntologyNode twotouch = new OntologyNode(Concept.TWO_TOUCH);
        OntologyNode fourtouch = new OntologyNode(Concept.FOUR_TOUCH);
        OntologyNode eighttouch = new OntologyNode(Concept.EIGHT_TOUCH);
        OntologyNode qualityset = new OntologyNode(Concept.QUALITY_SET);
        OntologyNode qualitycolour = new OntologyNode(Concept.QUALITY_COLOUR);
        OntologyNode qualitytaste = new OntologyNode(Concept.QUALITY_TASTE);
        OntologyNode qualitysmell = new OntologyNode(Concept.QUALITY_SMELL);
        OntologyNode qualitytouch = new OntologyNode(Concept.QUALITY_TOUCH);
        OntologyNode vargana = new OntologyNode(Concept.VARGAN);
        OntologyNode audarik = new OntologyNode(Concept.AUDARIK);
        OntologyNode vaikriya = new OntologyNode(Concept.VAIKRIYA);
        OntologyNode aharak = new OntologyNode(Concept.AHARAK);
        OntologyNode taijas = new OntologyNode(Concept.TAIJAS);
        OntologyNode karman = new OntologyNode(Concept.KARM);
        OntologyNode bhasha = new OntologyNode(Concept.BHASHA);
        OntologyNode shvasochhvas = new OntologyNode(Concept.SHVASOCHHVAS);
        OntologyNode manah = new OntologyNode(Concept.MANAH);
        OntologyNode ghati = new OntologyNode(Concept.GHAATI);
        OntologyNode aghati = new OntologyNode(Concept.AGHAATI);
        OntologyNode jnanavarniya = new OntologyNode(Concept.JNANAVARNIYA);
        OntologyNode darshanavarniya = new OntologyNode(Concept.DARSHANAVARNIYA);
        OntologyNode mohaniya = new OntologyNode(Concept.MOHANIYA);
        OntologyNode antaray = new OntologyNode(Concept.ANTARAY);
        OntologyNode jnanavarniyaclassification = new OntologyNode(Concept.JNANAVARNIYA_CLASSIFICATION);
        OntologyNode matijnanavarniya = new OntologyNode(Concept.MATI_JNANAVARNIYA);
        OntologyNode shrutjnanavarniya = new OntologyNode(Concept.SHRUT_JNANAVARNIYA);
        OntologyNode avadhijnanavarniya = new OntologyNode(Concept.AVADHI_JNANAVARNIYA);
        OntologyNode manahparyayajnanavarniya = new OntologyNode(Concept.MANAHPARYAYA_JNANAVARNIYA);
        OntologyNode kevalajnanavarniya = new OntologyNode(Concept.KEVALA_JNANAVARNIYA);
        OntologyNode darshanavarniyaclassification = new OntologyNode(Concept.DARSHANAVARNIYA_CLASSIFICATION);
        OntologyNode chakshudarshanavarniya = new OntologyNode(Concept.CHAKSHU_DARSHANAVARNIYA);
        OntologyNode achakshudarshanavarniya = new OntologyNode(Concept.ACHAKSHU_DARSHANAVARNIYA);
        OntologyNode avadhidarshanavarniya = new OntologyNode(Concept.AVADHI_DARSHANAVARNIYA);
        OntologyNode kevaladarshanavarniya = new OntologyNode(Concept.KEVALA_DARSHANAVARNIYA);
        OntologyNode nidra = new OntologyNode(Concept.NIDRA);
        OntologyNode nidranidra = new OntologyNode(Concept.NIDRA_NIDRA);
        OntologyNode prachala = new OntologyNode(Concept.PRACHALA);
        OntologyNode prachalaprachala = new OntologyNode(Concept.PRACHALA_PRACHALA);
        OntologyNode styanarddhi = new OntologyNode(Concept.STYANARDDHI);
        OntologyNode mohaniyaclassification = new OntologyNode(Concept.MOHANIYA_CLASSIFICATION);
        OntologyNode darshanamohaniya = new OntologyNode(Concept.DARSHANA_MOHANIYA);
        OntologyNode charitramohaniya = new OntologyNode(Concept.CHARITRA_MOHANIYA);
        OntologyNode darshanamohaniyaclassification = new OntologyNode(Concept.DARSHANA_MOHANIYA_CLASSIFICATION);
        OntologyNode mithyatva = new OntologyNode(Concept.MITHYATVA);
        OntologyNode samyaktvamohaniya = new OntologyNode(Concept.SAMYAKTVA_MOHANIYA);
        OntologyNode mishra = new OntologyNode(Concept.MISHRA);
        OntologyNode charitramohaniyaclassification = new OntologyNode(Concept.CHARITRA_MOHANIYA_CLASSIFICATION);
        OntologyNode kashaya = new OntologyNode(Concept.KASHAYA);
        OntologyNode nokashaya = new OntologyNode(Concept.NOKASHAYA);
        OntologyNode kashayaclassification = new OntologyNode(Concept.KASHAYA_CLASSIFICATION);
        OntologyNode krodh = new OntologyNode(Concept.KRODH);
        OntologyNode maan = new OntologyNode(Concept.MAAN);
        OntologyNode maya = new OntologyNode(Concept.MAYA);
        OntologyNode lobh = new OntologyNode(Concept.LOBH);
        OntologyNode krodhanantanubandhi = new OntologyNode(Concept.KRODH_ANANTANUBANDHI);
        OntologyNode krodhapratyakhyanavaraniya = new OntologyNode(Concept.KRODH_APRATYAKHYANAVARANIYA);
        OntologyNode krodhpratyakhyanavaraniya = new OntologyNode(Concept.KRODH_PRATYAKHYANAVARANIYA);
        OntologyNode krodhsanjvalan = new OntologyNode(Concept.KRODH_SANJVALAN);
        OntologyNode maananantanubandhi = new OntologyNode(Concept.MAAN_ANANTANUBANDHI);
        OntologyNode maanapratyakhyanavaraniya = new OntologyNode(Concept.MAAN_APRATYAKHYANAVARANIYA);
        OntologyNode maanpratyakhyanavaraniya = new OntologyNode(Concept.MAAN_PRATYAKHYANAVARANIYA);
        OntologyNode maansanjvalan = new OntologyNode(Concept.MAAN_SANJVALAN);
        OntologyNode mayaanantanubandhi = new OntologyNode(Concept.MAYA_ANANTANUBANDHI);
        OntologyNode mayaapratyakhyanavaraniya = new OntologyNode(Concept.MAYA_APRATYAKHYANAVARANIYA);
        OntologyNode mayapratyakhyanavaraniya = new OntologyNode(Concept.MAYA_PRATYAKHYANAVARANIYA);
        OntologyNode mayasanjvalan = new OntologyNode(Concept.MAYA_SANJVALAN);
        OntologyNode lobhanantanubandhi = new OntologyNode(Concept.LOBH_ANANTANUBANDHI);
        OntologyNode lobhapratyakhyanavaraniya = new OntologyNode(Concept.LOBH_APRATYAKHYANAVARANIYA);
        OntologyNode lobhpratyakhyanavaraniya = new OntologyNode(Concept.LOBH_PRATYAKHYANAVARANIYA);
        OntologyNode lobhsanjvalan = new OntologyNode(Concept.LOBH_SANJVALAN);
        OntologyNode nokashayaclassification = new OntologyNode(Concept.NOKASHAYA_CLASSIFICATION);
        OntologyNode hasya = new OntologyNode(Concept.HASYA);
        OntologyNode rati = new OntologyNode(Concept.RATI);
        OntologyNode arati = new OntologyNode(Concept.ARATI);
        OntologyNode shok = new OntologyNode(Concept.SHOK);
        OntologyNode bhaya = new OntologyNode(Concept.BHAYA);
        OntologyNode jugupsa = new OntologyNode(Concept.JUGUPSA);
        OntologyNode purushveda = new OntologyNode(Concept.PURUSHVEDA);
        OntologyNode striveda = new OntologyNode(Concept.STRIVEDA);
        OntologyNode napumsakaveda = new OntologyNode(Concept.NAPUMSAKAVEDA);
        OntologyNode antarayclassification = new OntologyNode(Concept.ANTARAY_CLASSIFICATION);
        OntologyNode danaantaray = new OntologyNode(Concept.DANA_ANTARAY);
        OntologyNode labhaantaray = new OntologyNode(Concept.LABHA_ANTARAY);
        OntologyNode bhogaantaray = new OntologyNode(Concept.BHOGA_ANTARAY);
        OntologyNode upabhogaantaray = new OntologyNode(Concept.UPABHOGA_ANTARAY);
        OntologyNode viryaantaray = new OntologyNode(Concept.VIRYA_ANTARAY);
        OntologyNode vedniya = new OntologyNode(Concept.VEDNIYA);
        OntologyNode nam = new OntologyNode(Concept.NAM);
        OntologyNode gotra = new OntologyNode(Concept.GOTRA);
        OntologyNode ayushya = new OntologyNode(Concept.AYUSHYA);
        OntologyNode vedniyaclassification = new OntologyNode(Concept.VEDNIYA_CLASSIFICATION);
        OntologyNode shatavedniya = new OntologyNode(Concept.SHATA_VEDNIYA);
        OntologyNode ashatavedniya = new OntologyNode(Concept.ASHATA_VEDNIYA);
        OntologyNode ayushyaclassification = new OntologyNode(Concept.AYUSHYA_CLASSIFICATION);
        OntologyNode devaayu = new OntologyNode(Concept.DEVA_AYU);
        OntologyNode manushyaayu = new OntologyNode(Concept.MANUSHYA_AYU);
        OntologyNode tiryanchayu = new OntologyNode(Concept.TIRYANCH_AYU);
        OntologyNode narakaayu = new OntologyNode(Concept.NARAKA_AYU);
        OntologyNode gotraclassification = new OntologyNode(Concept.GOTRA_CLASSIFICATION);
        OntologyNode ucchagotra = new OntologyNode(Concept.UCCHA_GOTRA);
        OntologyNode neechagotra = new OntologyNode(Concept.NEECHA_GOTRA);
        OntologyNode namclassification = new OntologyNode(Concept.NAM_CLASSIFICATION);
        OntologyNode gatinam = new OntologyNode(Concept.GATI_NAM);
        OntologyNode jatinam = new OntologyNode(Concept.JATI_NAM);
        OntologyNode shariranam = new OntologyNode(Concept.SHARIRA_NAM);
        OntologyNode angopanganam = new OntologyNode(Concept.ANGOPANGA_NAM);
        OntologyNode samhanananam = new OntologyNode(Concept.SAMHANANA_NAM);
        OntologyNode samsthananam = new OntologyNode(Concept.SAMSTHANA_NAM);
        OntologyNode varnanam = new OntologyNode(Concept.VARNA_NAM);
        OntologyNode gandhanam = new OntologyNode(Concept.GANDHA_NAM);
        OntologyNode rasanam = new OntologyNode(Concept.RASA_NAM);
        OntologyNode sparshanam = new OntologyNode(Concept.SPARSHA_NAM);
        OntologyNode anupurvinam = new OntologyNode(Concept.ANUPURVI_NAM);
        OntologyNode vihayogatinam = new OntologyNode(Concept.VIHAYOGATI_NAM);
        OntologyNode trasanam = new OntologyNode(Concept.TRASA_NAM);
        OntologyNode sthavaranam = new OntologyNode(Concept.STHAVARA_NAM);
        OntologyNode badaranam = new OntologyNode(Concept.BADARA_NAM);
        OntologyNode sukshmanam = new OntologyNode(Concept.SUKSHMA_NAM);
        OntologyNode paryaptanam = new OntologyNode(Concept.PARYAPTA_NAM);
        OntologyNode aparyaptanam = new OntologyNode(Concept.APARYAPTA_NAM);
        OntologyNode pratyekanam = new OntologyNode(Concept.PRATYEKA_NAM);
        OntologyNode sadharananam = new OntologyNode(Concept.SADHARANA_NAM);
        OntologyNode sthiranam = new OntologyNode(Concept.STHIRA_NAM);
        OntologyNode asthiranam = new OntologyNode(Concept.ASTHIRA_NAM);
        OntologyNode subhanam = new OntologyNode(Concept.SUBHA_NAM);
        OntologyNode asubhanam = new OntologyNode(Concept.ASUBHA_NAM);
        OntologyNode subhaganam = new OntologyNode(Concept.SUBHAGA_NAM);
        OntologyNode durbhaganam = new OntologyNode(Concept.DURBHAGA_NAM);
        OntologyNode susvaranam = new OntologyNode(Concept.SUSVARA_NAM);
        OntologyNode duhsvaranam = new OntologyNode(Concept.DUHSVARA_NAM);
        OntologyNode adeyanam = new OntologyNode(Concept.ADEYA_NAM);
        OntologyNode anadeyanam = new OntologyNode(Concept.ANADEYA_NAM);
        OntologyNode yashahkirtinam = new OntologyNode(Concept.YASHAHKIRTI_NAM);
        OntologyNode ayashahkirtinam = new OntologyNode(Concept.AYASHAHKIRTI_NAM);
        OntologyNode devagatinam = new OntologyNode(Concept.DEVA_GATI_NAM);
        OntologyNode manushyagatinam = new OntologyNode(Concept.MANUSHYA_GATI_NAM);
        OntologyNode tiryaggatinam = new OntologyNode(Concept.TIRYAG_GATI_NAM);
        OntologyNode narakagatinam = new OntologyNode(Concept.NARAKA_GATI_NAM);
        OntologyNode ekendriyajati = new OntologyNode(Concept.EKENDRIYA_JATI);
        OntologyNode dvindriyajati = new OntologyNode(Concept.DVINDRIYA_JATI);
        OntologyNode trindriyajati = new OntologyNode(Concept.TRINDRIYA_JATI);
        OntologyNode caturindriyajati = new OntologyNode(Concept.CATURINDRIYA_JATI);
        OntologyNode panchendriyajati = new OntologyNode(Concept.PANCHENDRIYA_JATI);
        OntologyNode audarikasharira = new OntologyNode(Concept.AUDARIKA_SHARIRA);
        OntologyNode vaikriyasharira = new OntologyNode(Concept.VAIKRIYA_SHARIRA);
        OntologyNode aharakasharira = new OntologyNode(Concept.AHARAKA_SHARIRA);
        OntologyNode taijasasharira = new OntologyNode(Concept.TAIJASA_SHARIRA);
        OntologyNode karmanasharira = new OntologyNode(Concept.KARMANA_SHARIRA);
        OntologyNode audarikaangopanga = new OntologyNode(Concept.AUDARIKA_ANGOPANGA);
        OntologyNode vaikriyaangopanga = new OntologyNode(Concept.VAIKRIYA_ANGOPANGA);
        OntologyNode aharakaangopanga = new OntologyNode(Concept.AHARAKA_ANGOPANGA);
        OntologyNode vajrarsabhanaraca = new OntologyNode(Concept.VAJRA_RSABHANARACA);
        OntologyNode rsabhanaraca = new OntologyNode(Concept.RSABHANARACA);
        OntologyNode naraca = new OntologyNode(Concept.NARACA);
        OntologyNode ardhnaraca = new OntologyNode(Concept.ARDH_NARACA);
        OntologyNode kilika = new OntologyNode(Concept.KILIKA);
        OntologyNode sevartta = new OntologyNode(Concept.SEVARTTA);
        OntologyNode samacaturasra = new OntologyNode(Concept.SAMACATURASRA);
        OntologyNode nyagrodhaparimandala = new OntologyNode(Concept.NYAGRODHAPARIMANDALA);
        OntologyNode sadi = new OntologyNode(Concept.SADI);
        OntologyNode kubja = new OntologyNode(Concept.KUBJA);
        OntologyNode vamana = new OntologyNode(Concept.VAMANA);
        OntologyNode hunda = new OntologyNode(Concept.HUNDA);
        OntologyNode krishnavarna = new OntologyNode(Concept.KRISHNA_VARNA);
        OntologyNode nilavarna = new OntologyNode(Concept.NILA_VARNA);
        OntologyNode lohitavarna = new OntologyNode(Concept.LOHITA_VARNA);
        OntologyNode haritavarna = new OntologyNode(Concept.HARITA_VARNA);
        OntologyNode suklavarna = new OntologyNode(Concept.SUKLA_VARNA);
        OntologyNode surabhigandha = new OntologyNode(Concept.SURABHI_GANDHA);
        OntologyNode durabhigandha = new OntologyNode(Concept.DURABHI_GANDHA);
        OntologyNode tiktarasa = new OntologyNode(Concept.TIKTA_RASA);
        OntologyNode katurasa = new OntologyNode(Concept.KATU_RASA);
        OntologyNode kasayarasa = new OntologyNode(Concept.KASAYA_RASA);
        OntologyNode amlarasa = new OntologyNode(Concept.AMLA_RASA);
        OntologyNode madhurarasa = new OntologyNode(Concept.MADHURA_RASA);
        OntologyNode gurusparsha = new OntologyNode(Concept.GURU_SPARSHA);
        OntologyNode laghusparsha = new OntologyNode(Concept.LAGHU_SPARSHA);
        OntologyNode mridusparsha = new OntologyNode(Concept.MRIDU_SPARSHA);
        OntologyNode kathorsparsha = new OntologyNode(Concept.KATHOR_SPARSHA);
        OntologyNode snigdhasparsha = new OntologyNode(Concept.SNIGDHA_SPARSHA);
        OntologyNode rukshasparsha = new OntologyNode(Concept.RUKSHA_SPARSHA);
        OntologyNode sheetasparsha = new OntologyNode(Concept.SHEETA_SPARSHA);
        OntologyNode ushnasparsha = new OntologyNode(Concept.USHNA_SPARSHA);
        OntologyNode devaanupurvi = new OntologyNode(Concept.DEVA_ANUPURVI);
        OntologyNode manushyaanupurvi = new OntologyNode(Concept.MANUSHYA_ANUPURVI);
        OntologyNode tiryanchanupurvi = new OntologyNode(Concept.TIRYANCH_ANUPURVI);
        OntologyNode narakaanupurvi = new OntologyNode(Concept.NARAKA_ANUPURVI);
        OntologyNode prasastavihayogati = new OntologyNode(Concept.PRASASTA_VIHAYOGATI);
        OntologyNode aprasastavihayogati = new OntologyNode(Concept.APRASASTA_VIHAYOGATI);
        OntologyNode trasafully = new OntologyNode(Concept.TRASA_FULLY);
        OntologyNode sthavarafully = new OntologyNode(Concept.STHAVARA_FULLY);
        OntologyNode badarafully = new OntologyNode(Concept.BADARA_FULLY);
        OntologyNode sukshmafully = new OntologyNode(Concept.SUKSHMA_FULLY);
        OntologyNode paryaptafully = new OntologyNode(Concept.PARYAPTA_FULLY);
        OntologyNode aparyaptafully = new OntologyNode(Concept.APARYAPTA_FULLY);
        OntologyNode pratyekafully = new OntologyNode(Concept.PRATYEKA_FULLY);
        OntologyNode sadharanafully = new OntologyNode(Concept.SADHARANA_FULLY);
        OntologyNode sthirafully = new OntologyNode(Concept.STHIRA_FULLY);
        OntologyNode asthirafully = new OntologyNode(Concept.ASTHIRA_FULLY);
        OntologyNode subhafully = new OntologyNode(Concept.SUBHA_FULLY);
        OntologyNode asubhafully = new OntologyNode(Concept.ASUBHA_FULLY);
        OntologyNode subhagafully = new OntologyNode(Concept.SUBHAGA_FULLY);
        OntologyNode durbhagafully = new OntologyNode(Concept.DURBHAGA_FULLY);
        OntologyNode susvarafully = new OntologyNode(Concept.SUSVARA_FULLY);
        OntologyNode duhsvarafully = new OntologyNode(Concept.DUHSVARA_FULLY);
        OntologyNode adeyafully = new OntologyNode(Concept.ADEYA_FULLY);
        OntologyNode anadeyafully = new OntologyNode(Concept.ANADEYA_FULLY);
        OntologyNode yashahkirtifully = new OntologyNode(Concept.YASHAHKIRTI_FULLY);
        OntologyNode ayashahkirtifully = new OntologyNode(Concept.AYASHAHKIRTI_FULLY);

        dravya.addChild(astikay);
        dravya.addChild(nastikay);
        nastikay.addChild(kaal);
        kaal.addChild(samay);
        kaal.addChild(avali);
        astikay.addChild(jeev);
        astikay.addChild(ajiv);
        ajiv.addChild(dharm);
        ajiv.addChild(adharm);
        ajiv.addChild(akash);
        ajiv.addChild(pudgal);
        akash.addChild(lokakash);
        akash.addChild(alokakash);
        jeev.addChild(mukta);
        jeev.addChild(sansari);
        sansari.addChild(sthavar);
        sansari.addChild(tras);
        sthavar.addChild(prithvikay);
        sthavar.addChild(apkay);
        sthavar.addChild(teukay);
        sthavar.addChild(vayukay);
        sthavar.addChild(vanaspatikay);
        vanaspatikay.addChild(pratyek);
        vanaspatikay.addChild(sadharan);
        sthavar.addChild(sthavarsize);
        sthavarsize.addChild(badarjeev);
        sthavarsize.addChild(sukshmajeev);
        tras.addChild(dwindriya);
        tras.addChild(trindriya);
        tras.addChild(chaurindriya);
        tras.addChild(panchendriya);
        panchendriya.addChild(saini);
        panchendriya.addChild(asaini);
        sansari.addChild(gaticlassification);
        gaticlassification.addChild(dev);
        gaticlassification.addChild(manushya);
        gaticlassification.addChild(tiryanch);
        gaticlassification.addChild(narak);
        sansari.addChild(pranaclassification);
        pranaclassification.addChild(indriyaprana);
        pranaclassification.addChild(balaprana);
        pranaclassification.addChild(ayushyaprana);
        pranaclassification.addChild(shvasochchhvasprana);
        indriyaprana.addChild(sparshindriya);
        indriyaprana.addChild(rasindriya);
        indriyaprana.addChild(ghranindriya);
        indriyaprana.addChild(chakshuindriya);
        indriyaprana.addChild(shravanindriya);
        balaprana.addChild(manobala);
        balaprana.addChild(vachanbala);
        balaprana.addChild(kayabala);
        pudgal.addChild(murta);
        murta.addChild(rupatva);
        rupatva.addChild(colour);
        rupatva.addChild(taste);
        rupatva.addChild(smell);
        rupatva.addChild(touch);
        colour.addChild(black);
        colour.addChild(blue);
        colour.addChild(red);
        colour.addChild(yellow);
        colour.addChild(white);
        taste.addChild(sweet);
        taste.addChild(bitter);
        taste.addChild(pungent);
        taste.addChild(sour);
        taste.addChild(astringent);
        smell.addChild(goodsmell);
        smell.addChild(badsmell);
        touch.addChild(cold);
        touch.addChild(hot);
        touch.addChild(smooth);
        touch.addChild(rough);
        touch.addChild(light);
        touch.addChild(heavy);
        touch.addChild(soft);
        touch.addChild(hard);
        pudgal.addChild(stateclassification);
        pudgal.addChild(structureclassification);
        pudgal.addChild(touchbasedclassification);
        pudgal.addChild(functionclassification);
        pudgal.addChild(pudgalqualityclassification);
        pudgal.addChild(aharmethodology);
        aharmethodology.addChild(ojahar);
        aharmethodology.addChild(romahar);
        aharmethodology.addChild(kavalahar);
        aharmethodology.addChild(lepahar);
        aharmethodology.addChild(manasahar);
        aharmethodology.addChild(karmanahar);
        kavalahar.addChild(kavalaharclassification);
        kavalaharclassification.addChild(asanam);
        kavalaharclassification.addChild(paanam);
        kavalaharclassification.addChild(khaimam);
        kavalaharclassification.addChild(saimam);
        stateclassification.addChild(sthulasthula);
        stateclassification.addChild(sthula);
        stateclassification.addChild(sthulasukshma);
        stateclassification.addChild(sukshmasthula);
        stateclassification.addChild(sukshma);
        stateclassification.addChild(sukshmasukshma);
        structureclassification.addChild(paramanu);
        structureclassification.addChild(skandh);
        touchbasedclassification.addChild(twotouch);
        touchbasedclassification.addChild(fourtouch);
        touchbasedclassification.addChild(eighttouch);
        pudgalqualityclassification.addChild(qualityset);
        qualityset.addChild(qualitycolour);
        qualityset.addChild(qualitytaste);
        qualityset.addChild(qualitysmell);
        qualityset.addChild(qualitytouch);
        functionclassification.addChild(vargana);
        vargana.addChild(audarik);
        vargana.addChild(vaikriya);
        vargana.addChild(aharak);
        vargana.addChild(taijas);
        vargana.addChild(karman);
        vargana.addChild(bhasha);
        vargana.addChild(shvasochhvas);
        vargana.addChild(manah);
        karman.addChild(ghati);
        karman.addChild(aghati);
        ghati.addChild(jnanavarniya);
        ghati.addChild(darshanavarniya);
        ghati.addChild(mohaniya);
        ghati.addChild(antaray);
        jnanavarniya.addChild(jnanavarniyaclassification);
        jnanavarniyaclassification.addChild(matijnanavarniya);
        jnanavarniyaclassification.addChild(shrutjnanavarniya);
        jnanavarniyaclassification.addChild(avadhijnanavarniya);
        jnanavarniyaclassification.addChild(manahparyayajnanavarniya);
        jnanavarniyaclassification.addChild(kevalajnanavarniya);
        darshanavarniya.addChild(darshanavarniyaclassification);
        darshanavarniyaclassification.addChild(chakshudarshanavarniya);
        darshanavarniyaclassification.addChild(achakshudarshanavarniya);
        darshanavarniyaclassification.addChild(avadhidarshanavarniya);
        darshanavarniyaclassification.addChild(kevaladarshanavarniya);
        darshanavarniyaclassification.addChild(nidra);
        darshanavarniyaclassification.addChild(nidranidra);
        darshanavarniyaclassification.addChild(prachala);
        darshanavarniyaclassification.addChild(prachalaprachala);
        darshanavarniyaclassification.addChild(styanarddhi);
        mohaniya.addChild(mohaniyaclassification);
        mohaniyaclassification.addChild(darshanamohaniya);
        mohaniyaclassification.addChild(charitramohaniya);
        darshanamohaniya.addChild(darshanamohaniyaclassification);
        darshanamohaniyaclassification.addChild(mithyatva);
        darshanamohaniyaclassification.addChild(samyaktvamohaniya);
        darshanamohaniyaclassification.addChild(mishra);
        charitramohaniya.addChild(charitramohaniyaclassification);
        charitramohaniyaclassification.addChild(kashaya);
        charitramohaniyaclassification.addChild(nokashaya);
        kashaya.addChild(kashayaclassification);
        kashayaclassification.addChild(krodh);
        kashayaclassification.addChild(maan);
        kashayaclassification.addChild(maya);
        kashayaclassification.addChild(lobh);
        krodh.addChild(krodhanantanubandhi);
        krodh.addChild(krodhapratyakhyanavaraniya);
        krodh.addChild(krodhpratyakhyanavaraniya);
        krodh.addChild(krodhsanjvalan);
        maan.addChild(maananantanubandhi);
        maan.addChild(maanapratyakhyanavaraniya);
        maan.addChild(maanpratyakhyanavaraniya);
        maan.addChild(maansanjvalan);
        maya.addChild(mayaanantanubandhi);
        maya.addChild(mayaapratyakhyanavaraniya);
        maya.addChild(mayapratyakhyanavaraniya);
        maya.addChild(mayasanjvalan);
        lobh.addChild(lobhanantanubandhi);
        lobh.addChild(lobhapratyakhyanavaraniya);
        lobh.addChild(lobhpratyakhyanavaraniya);
        lobh.addChild(lobhsanjvalan);
        nokashaya.addChild(nokashayaclassification);
        nokashayaclassification.addChild(hasya);
        nokashayaclassification.addChild(rati);
        nokashayaclassification.addChild(arati);
        nokashayaclassification.addChild(shok);
        nokashayaclassification.addChild(bhaya);
        nokashayaclassification.addChild(jugupsa);
        nokashayaclassification.addChild(purushveda);
        nokashayaclassification.addChild(striveda);
        nokashayaclassification.addChild(napumsakaveda);
        antaray.addChild(antarayclassification);
        antarayclassification.addChild(danaantaray);
        antarayclassification.addChild(labhaantaray);
        antarayclassification.addChild(bhogaantaray);
        antarayclassification.addChild(upabhogaantaray);
        antarayclassification.addChild(viryaantaray);
        aghati.addChild(vedniya);
        aghati.addChild(nam);
        aghati.addChild(gotra);
        aghati.addChild(ayushya);
        vedniya.addChild(vedniyaclassification);
        vedniyaclassification.addChild(shatavedniya);
        vedniyaclassification.addChild(ashatavedniya);
        ayushya.addChild(ayushyaclassification);
        ayushyaclassification.addChild(devaayu);
        ayushyaclassification.addChild(manushyaayu);
        ayushyaclassification.addChild(tiryanchayu);
        ayushyaclassification.addChild(narakaayu);
        gotra.addChild(gotraclassification);
        gotraclassification.addChild(ucchagotra);
        gotraclassification.addChild(neechagotra);
        nam.addChild(namclassification);
        namclassification.addChild(gatinam);
        namclassification.addChild(jatinam);
        namclassification.addChild(shariranam);
        namclassification.addChild(angopanganam);
        namclassification.addChild(samhanananam);
        namclassification.addChild(samsthananam);
        namclassification.addChild(varnanam);
        namclassification.addChild(gandhanam);
        namclassification.addChild(rasanam);
        namclassification.addChild(sparshanam);
        namclassification.addChild(anupurvinam);
        namclassification.addChild(vihayogatinam);
        namclassification.addChild(trasanam);
        namclassification.addChild(sthavaranam);
        namclassification.addChild(badaranam);
        namclassification.addChild(sukshmanam);
        namclassification.addChild(paryaptanam);
        namclassification.addChild(aparyaptanam);
        namclassification.addChild(pratyekanam);
        namclassification.addChild(sadharananam);
        namclassification.addChild(sthiranam);
        namclassification.addChild(asthiranam);
        namclassification.addChild(subhanam);
        namclassification.addChild(asubhanam);
        namclassification.addChild(subhaganam);
        namclassification.addChild(durbhaganam);
        namclassification.addChild(susvaranam);
        namclassification.addChild(duhsvaranam);
        namclassification.addChild(adeyanam);
        namclassification.addChild(anadeyanam);
        namclassification.addChild(yashahkirtinam);
        namclassification.addChild(ayashahkirtinam);
        gatinam.addChild(devagatinam);
        gatinam.addChild(manushyagatinam);
        gatinam.addChild(tiryaggatinam);
        gatinam.addChild(narakagatinam);
        jatinam.addChild(ekendriyajati);
        jatinam.addChild(dvindriyajati);
        jatinam.addChild(trindriyajati);
        jatinam.addChild(caturindriyajati);
        jatinam.addChild(panchendriyajati);
        shariranam.addChild(audarikasharira);
        shariranam.addChild(vaikriyasharira);
        shariranam.addChild(aharakasharira);
        shariranam.addChild(taijasasharira);
        shariranam.addChild(karmanasharira);
        angopanganam.addChild(audarikaangopanga);
        angopanganam.addChild(vaikriyaangopanga);
        angopanganam.addChild(aharakaangopanga);
        samhanananam.addChild(vajrarsabhanaraca);
        samhanananam.addChild(rsabhanaraca);
        samhanananam.addChild(naraca);
        samhanananam.addChild(ardhnaraca);
        samhanananam.addChild(kilika);
        samhanananam.addChild(sevartta);
        samsthananam.addChild(samacaturasra);
        samsthananam.addChild(nyagrodhaparimandala);
        samsthananam.addChild(sadi);
        samsthananam.addChild(kubja);
        samsthananam.addChild(vamana);
        samsthananam.addChild(hunda);
        varnanam.addChild(krishnavarna);
        varnanam.addChild(nilavarna);
        varnanam.addChild(lohitavarna);
        varnanam.addChild(haritavarna);
        varnanam.addChild(suklavarna);
        gandhanam.addChild(surabhigandha);
        gandhanam.addChild(durabhigandha);
        rasanam.addChild(tiktarasa);
        rasanam.addChild(katurasa);
        rasanam.addChild(kasayarasa);
        rasanam.addChild(amlarasa);
        rasanam.addChild(madhurarasa);
        sparshanam.addChild(gurusparsha);
        sparshanam.addChild(laghusparsha);
        sparshanam.addChild(mridusparsha);
        sparshanam.addChild(kathorsparsha);
        sparshanam.addChild(snigdhasparsha);
        sparshanam.addChild(rukshasparsha);
        sparshanam.addChild(sheetasparsha);
        sparshanam.addChild(ushnasparsha);
        anupurvinam.addChild(devaanupurvi);
        anupurvinam.addChild(manushyaanupurvi);
        anupurvinam.addChild(tiryanchanupurvi);
        anupurvinam.addChild(narakaanupurvi);
        vihayogatinam.addChild(prasastavihayogati);
        vihayogatinam.addChild(aprasastavihayogati);
        trasanam.addChild(trasafully);
        sthavaranam.addChild(sthavarafully);
        badaranam.addChild(badarafully);
        sukshmanam.addChild(sukshmafully);
        paryaptanam.addChild(paryaptafully);
        aparyaptanam.addChild(aparyaptafully);
        pratyekanam.addChild(pratyekafully);
        sadharananam.addChild(sadharanafully);
        sthiranam.addChild(sthirafully);
        asthiranam.addChild(asthirafully);
        subhanam.addChild(subhafully);
        asubhanam.addChild(asubhafully);
        subhaganam.addChild(subhagafully);
        durbhaganam.addChild(durbhagafully);
        susvaranam.addChild(susvarafully);
        duhsvaranam.addChild(duhsvarafully);
        adeyanam.addChild(adeyafully);
        anadeyanam.addChild(anadeyafully);
        yashahkirtinam.addChild(yashahkirtifully);
        ayashahkirtinam.addChild(ayashahkirtifully);

        // Returning DRAVYA as root, although other roots might exist in disconnected parts,
        // but Dravya is the foundational philosophical element.
        return dravya;
    }
}
